//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Net.Node.MAUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Net.Node.MAUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main ultranet wallet.
        /// </summary>
        internal static string DefaultWalletName {
            get {
                return ResourceManager.GetString("DefaultWalletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold the search bar. Tap the three dots icon More then Settings. Turn Search Box Effects on or off. .
        /// </summary>
        internal static string HelpAnswer1 {
            get {
                return ResourceManager.GetString("HelpAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following icons are located in the upper right corner of the screen or in the quick settings panel. To see their names and descriptions, swipe down twice from the top of the screen..
        /// </summary>
        internal static string HelpAnswer2 {
            get {
                return ResourceManager.GetString("HelpAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpLine1 {
            get {
                return ResourceManager.GetString("HelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpLine10 {
            get {
                return ResourceManager.GetString("HelpLine10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpLine11 {
            get {
                return ResourceManager.GetString("HelpLine11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpLine12 {
            get {
                return ResourceManager.GetString("HelpLine12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpLine13 {
            get {
                return ResourceManager.GetString("HelpLine13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpLine2 {
            get {
                return ResourceManager.GetString("HelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpLine3 {
            get {
                return ResourceManager.GetString("HelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpLine4 {
            get {
                return ResourceManager.GetString("HelpLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpLine5 {
            get {
                return ResourceManager.GetString("HelpLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpLine6 {
            get {
                return ResourceManager.GetString("HelpLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpLine7 {
            get {
                return ResourceManager.GetString("HelpLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpLine8 {
            get {
                return ResourceManager.GetString("HelpLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpLine9 {
            get {
                return ResourceManager.GetString("HelpLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion1 {
            get {
                return ResourceManager.GetString("HelpQuestion1", resourceCulture);
            }
        }
    }
}
