export type OperationType =
  | "analysisResultUpdation"
  | "authorBid"
  | "authorMigration"
  | "authorRegistration"
  | "authorTransfer"
  | "candidacyDeclaration"
  | "emission"
  | "resourceCreation"
  | "resourceDeletion"
  | "resourceLinkCreation"
  | "resourceLinkDeletion"
  | "resourceUpdation"
  | "untTransfer"
