export type FairOperationType =
  | "AccountNicknameChange"
  | "FavoriteSiteChange"
  | "FileCreation"
  | "FileDeletion"
  | "PerpetualVoting"
  | "ProposalCreation"
  | "ProposalCommentCreation"
  | "ProposalVoting"
  | "UserFreeCreation"
