export type FairOperationType =
  | "AccountNicknameChange"
  | "FavoriteStoreChange"
  | "FileCreation"
  | "FileDeletion"
  | "PerpetualVoting"
  | "ProposalCreation"
  | "ProposalCommentCreation"
  | "ProposalVoting"
  | "UserAvatarChange"
  | "UserCreation"
