export const DEFAULT_PAGE_SIZE = 20

export const GROUP_DELIMITER = ","

export const DECIMAL_DELIMITER = "."

export const AUCTIONS_ITEMS_PER_PAGE_OPTIONS = [10, 15, 30]

export const AUCTIONS_ITEMS_PER_PAGE_DEFAULT_VALUE = AUCTIONS_ITEMS_PER_PAGE_OPTIONS[0]
