<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>

    <EnableNETAnalyzers>false</EnableNETAnalyzers>

    <StartupObject></StartupObject>

    <ApplicationIcon />

    <OutputType>Exe</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nexus\Uccs.Nexus.csproj" />
  </ItemGroup>

</Project>
