//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Additional_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Additional_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Additional_Strings", typeof(Additional_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Message.
        /// </summary>
        internal static string Alert_Message {
            get {
                return ResourceManager.GetString("Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Alert_Ok {
            get {
                return ResourceManager.GetString("Alert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Error_Default {
            get {
                return ResourceManager.GetString("Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string Error_DefaultTitle {
            get {
                return ResourceManager.GetString("Error_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file error.
        /// </summary>
        internal static string Error_LoadingFile {
            get {
                return ResourceManager.GetString("Error_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pincode.
        /// </summary>
        internal static string Error_PinCode {
            get {
                return ResourceManager.GetString("Error_PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From private key.
        /// </summary>
        internal static string From_PrivateKey {
            get {
                return ResourceManager.GetString("From_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From wallet file.
        /// </summary>
        internal static string From_WalletFile {
            get {
                return ResourceManager.GetString("From_WalletFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensations that people experience as they interact with the material world.
        /// </summary>
        internal static string Version4_Fix1 {
            get {
                return ResourceManager.GetString("Version4_Fix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cted to the terroristic phase of the revolution.
        /// </summary>
        internal static string Version4_Fix2 {
            get {
                return ResourceManager.GetString("Version4_Fix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extending the vocabulary beyond what the general reader already possessed.
        /// </summary>
        internal static string Version4_Fix3 {
            get {
                return ResourceManager.GetString("Version4_Fix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term was coined by Antoine Destutt de Tracy.
        /// </summary>
        internal static string Version4_Update1 {
            get {
                return ResourceManager.GetString("Version4_Update1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And philosopher, who conceived it in 1796.
        /// </summary>
        internal static string Version4_Update2 {
            get {
                return ResourceManager.GetString("Version4_Update2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To develop a rational system of ideas to oppose the.
        /// </summary>
        internal static string Version4_Update3 {
            get {
                return ResourceManager.GetString("Version4_Update3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a wallet file.
        /// </summary>
        internal static string WalletFile_Select {
            get {
                return ResourceManager.GetString("WalletFile_Select", resourceCulture);
            }
        }
    }
}
