//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Additional_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Additional_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Additional_Strings", typeof(Additional_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Message.
        /// </summary>
        internal static string Alert_Message {
            get {
                return ResourceManager.GetString("Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Alert_Ok {
            get {
                return ResourceManager.GetString("Alert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a bid.
        /// </summary>
        internal static string Author_MakeABid {
            get {
                return ResourceManager.GetString("Author_MakeABid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Author_Register {
            get {
                return ResourceManager.GetString("Author_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string Author_Renew {
            get {
                return ResourceManager.GetString("Author_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Author_Transfer {
            get {
                return ResourceManager.GetString("Author_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DeleteAccount_Cancel {
            get {
                return ResourceManager.GetString("DeleteAccount_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string DeleteAccount_Confirmation {
            get {
                return ResourceManager.GetString("DeleteAccount_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteAccount_Confirmation2 {
            get {
                return ResourceManager.GetString("DeleteAccount_Confirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to delete account please specify next text.
        /// </summary>
        internal static string DeleteAccount_SpecifyText {
            get {
                return ResourceManager.GetString("DeleteAccount_SpecifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Error_Default {
            get {
                return ResourceManager.GetString("Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string Error_DefaultTitle {
            get {
                return ResourceManager.GetString("Error_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file error.
        /// </summary>
        internal static string Error_LoadingFile {
            get {
                return ResourceManager.GetString("Error_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pincode.
        /// </summary>
        internal static string Error_PinCode {
            get {
                return ResourceManager.GetString("Error_PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From private key.
        /// </summary>
        internal static string From_PrivateKey {
            get {
                return ResourceManager.GetString("From_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From wallet file.
        /// </summary>
        internal static string From_WalletFile {
            get {
                return ResourceManager.GetString("From_WalletFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode was detected!.
        /// </summary>
        internal static string Message_BarcodeDetected {
            get {
                return ResourceManager.GetString("Message_BarcodeDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string Message_Copied {
            get {
                return ResourceManager.GetString("Message_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created!.
        /// </summary>
        internal static string Message_Created {
            get {
                return ResourceManager.GetString("Message_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted!.
        /// </summary>
        internal static string Message_Deleted {
            get {
                return ResourceManager.GetString("Message_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin was created.
        /// </summary>
        internal static string Message_PinCreated {
            get {
                return ResourceManager.GetString("Message_PinCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered!.
        /// </summary>
        internal static string Message_Registered {
            get {
                return ResourceManager.GetString("Message_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored!.
        /// </summary>
        internal static string Message_Restored {
            get {
                return ResourceManager.GetString("Message_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully transfered!.
        /// </summary>
        internal static string Message_Transfered {
            get {
                return ResourceManager.GetString("Message_Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Models_Days {
            get {
                return ResourceManager.GetString("Models_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Notification_Date {
            get {
                return ResourceManager.GetString("Notification_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Read.
        /// </summary>
        internal static string Notification_MarkAsRead {
            get {
                return ResourceManager.GetString("Notification_MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Notification_Severity {
            get {
                return ResourceManager.GetString("Notification_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification_Title {
            get {
                return ResourceManager.GetString("Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Product_Transfer {
            get {
                return ResourceManager.GetString("Product_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient UNT address.
        /// </summary>
        internal static string RecipientAccount_Address {
            get {
                return ResourceManager.GetString("RecipientAccount_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RecipientAccount_Cancel {
            get {
                return ResourceManager.GetString("RecipientAccount_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string RecipientAccount_Continue {
            get {
                return ResourceManager.GetString("RecipientAccount_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string RecipientAccount_External {
            get {
                return ResourceManager.GetString("RecipientAccount_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string RecipientAccount_Local {
            get {
                return ResourceManager.GetString("RecipientAccount_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Ethereum account private key.
        /// </summary>
        internal static string RecipientAccount_PrivateKey {
            get {
                return ResourceManager.GetString("RecipientAccount_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string RecipientAccount_QrCode {
            get {
                return ResourceManager.GetString("RecipientAccount_QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Account.
        /// </summary>
        internal static string RecipientAccount_Title {
            get {
                return ResourceManager.GetString("RecipientAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string SelectAuthor_Confirm {
            get {
                return ResourceManager.GetString("SelectAuthor_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select author to transfer.
        /// </summary>
        internal static string SelectAuthor_Title {
            get {
                return ResourceManager.GetString("SelectAuthor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string SourceAccount_Confirm {
            get {
                return ResourceManager.GetString("SourceAccount_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Account.
        /// </summary>
        internal static string SourceAccount_Title {
            get {
                return ResourceManager.GetString("SourceAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmations.
        /// </summary>
        internal static string Transaction_Confirmations {
            get {
                return ResourceManager.GetString("Transaction_Confirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Transaction Hash.
        /// </summary>
        internal static string Transaction_CopyHash {
            get {
                return ResourceManager.GetString("Transaction_CopyHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string Transaction_DateAndTime {
            get {
                return ResourceManager.GetString("Transaction_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string Transaction_Hash {
            get {
                return ResourceManager.GetString("Transaction_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Transaction_Size {
            get {
                return ResourceManager.GetString("Transaction_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Transaction_Status {
            get {
                return ResourceManager.GetString("Transaction_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction_Title {
            get {
                return ResourceManager.GetString("Transaction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensations that people experience as they interact with the material world.
        /// </summary>
        internal static string Version4_Fix1 {
            get {
                return ResourceManager.GetString("Version4_Fix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cted to the terroristic phase of the revolution.
        /// </summary>
        internal static string Version4_Fix2 {
            get {
                return ResourceManager.GetString("Version4_Fix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extending the vocabulary beyond what the general reader already possessed.
        /// </summary>
        internal static string Version4_Fix3 {
            get {
                return ResourceManager.GetString("Version4_Fix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term was coined by Antoine Destutt de Tracy.
        /// </summary>
        internal static string Version4_Update1 {
            get {
                return ResourceManager.GetString("Version4_Update1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And philosopher, who conceived it in 1796.
        /// </summary>
        internal static string Version4_Update2 {
            get {
                return ResourceManager.GetString("Version4_Update2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To develop a rational system of ideas to oppose the.
        /// </summary>
        internal static string Version4_Update3 {
            get {
                return ResourceManager.GetString("Version4_Update3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a wallet file.
        /// </summary>
        internal static string WalletFile_Select {
            get {
                return ResourceManager.GetString("WalletFile_Select", resourceCulture);
            }
        }
    }
}
