//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Author_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Author_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Author_Strings", typeof(Author_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left.
        /// </summary>
        internal static string Auction_DaysLeft {
            get {
                return ResourceManager.GetString("Auction_DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in.
        /// </summary>
        internal static string Auction_Expires {
            get {
                return ResourceManager.GetString("Auction_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Author_Amount {
            get {
                return ResourceManager.GetString("Author_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and more.
        /// </summary>
        internal static string Author_AndMore {
            get {
                return ResourceManager.GetString("Author_AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction ends.
        /// </summary>
        internal static string Author_AuctionEnd {
            get {
                return ResourceManager.GetString("Author_AuctionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid by.
        /// </summary>
        internal static string Author_BidBy {
            get {
                return ResourceManager.GetString("Author_BidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bid.
        /// </summary>
        internal static string Author_CurrentBid {
            get {
                return ResourceManager.GetString("Author_CurrentBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Author_Date {
            get {
                return ResourceManager.GetString("Author_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Details.
        /// </summary>
        internal static string Author_Details {
            get {
                return ResourceManager.GetString("Author_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired at.
        /// </summary>
        internal static string Author_Expired {
            get {
                return ResourceManager.GetString("Author_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author from Authors List.
        /// </summary>
        internal static string Author_FromList {
            get {
                return ResourceManager.GetString("Author_FromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Author_Hide {
            get {
                return ResourceManager.GetString("Author_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a bid.
        /// </summary>
        internal static string Author_MakeABid {
            get {
                return ResourceManager.GetString("Author_MakeABid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum bid by.
        /// </summary>
        internal static string Author_MaxBid {
            get {
                return ResourceManager.GetString("Author_MaxBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Author_Name {
            get {
                return ResourceManager.GetString("Author_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Author_Owner {
            get {
                return ResourceManager.GetString("Author_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Author_Products {
            get {
                return ResourceManager.GetString("Author_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Author_Register {
            get {
                return ResourceManager.GetString("Author_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string Author_Renew {
            get {
                return ResourceManager.GetString("Author_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Author_Status {
            get {
                return ResourceManager.GetString("Author_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Author_Title {
            get {
                return ResourceManager.GetString("Author_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Author_Transfer {
            get {
                return ResourceManager.GetString("Author_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors_Title {
            get {
                return ResourceManager.GetString("Authors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current bid.
        /// </summary>
        internal static string Bid_Current {
            get {
                return ResourceManager.GetString("Bid_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have higher bid.
        /// </summary>
        internal static string Bid_Higher {
            get {
                return ResourceManager.GetString("Bid_Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not leading.
        /// </summary>
        internal static string Bid_Lower {
            get {
                return ResourceManager.GetString("Bid_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        internal static string Filter_Auction {
            get {
                return ResourceManager.GetString("Filter_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Filter_Free {
            get {
                return ResourceManager.GetString("Filter_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Filter_Hidden {
            get {
                return ResourceManager.GetString("Filter_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        internal static string Filter_Owned {
            get {
                return ResourceManager.GetString("Filter_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string Filter_Reserved {
            get {
                return ResourceManager.GetString("Filter_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        internal static string Filter_Watched {
            get {
                return ResourceManager.GetString("Filter_Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name.
        /// </summary>
        internal static string MakeBid_AuthorName {
            get {
                return ResourceManager.GetString("MakeBid_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized author&apos;s name.
        /// </summary>
        internal static string MakeBid_AuthorName2 {
            get {
                return ResourceManager.GetString("MakeBid_AuthorName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm a bid?.
        /// </summary>
        internal static string MakeBid_Confirm {
            get {
                return ResourceManager.GetString("MakeBid_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Confirm&apos; button to confirm the bid.
        /// </summary>
        internal static string MakeBid_Confirm2 {
            get {
                return ResourceManager.GetString("MakeBid_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your bid.
        /// </summary>
        internal static string MakeBid_MakeYourBid {
            get {
                return ResourceManager.GetString("MakeBid_MakeYourBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your bid. Your bid should be higher than current bid in order to win Auction.
        /// </summary>
        internal static string MakeBid_MakeYourBid2 {
            get {
                return ResourceManager.GetString("MakeBid_MakeYourBid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Account.
        /// </summary>
        internal static string MakeBid_PaymentAccount {
            get {
                return ResourceManager.GetString("MakeBid_PaymentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string MakeBid_Summary {
            get {
                return ResourceManager.GetString("MakeBid_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With name:.
        /// </summary>
        internal static string MakeBid_Summary2 {
            get {
                return ResourceManager.GetString("MakeBid_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With price:.
        /// </summary>
        internal static string MakeBid_Summary3 {
            get {
                return ResourceManager.GetString("MakeBid_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string MakeBid_Summary4 {
            get {
                return ResourceManager.GetString("MakeBid_Summary4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Bid.
        /// </summary>
        internal static string MakeBid_Title {
            get {
                return ResourceManager.GetString("MakeBid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid.
        /// </summary>
        internal static string MakeBid_YourBid {
            get {
                return ResourceManager.GetString("MakeBid_YourBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNT amount.
        /// </summary>
        internal static string Registration_Comission {
            get {
                return ResourceManager.GetString("Registration_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm registration of this author?.
        /// </summary>
        internal static string Registration_Confirm {
            get {
                return ResourceManager.GetString("Registration_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Confirm&apos; button, registration will start.
        /// </summary>
        internal static string Registration_Confirm2 {
            get {
                return ResourceManager.GetString("Registration_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your payment account and Author title.
        /// </summary>
        internal static string Registration_Instruction {
            get {
                return ResourceManager.GetString("Registration_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your need specify your source, destination accounts and amount to transfer.
        /// </summary>
        internal static string Registration_Instruction2 {
            get {
                return ResourceManager.GetString("Registration_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Registration_Name {
            get {
                return ResourceManager.GetString("Registration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Author name. This name will be used like an application domain.
        /// </summary>
        internal static string Registration_Name2 {
            get {
                return ResourceManager.GetString("Registration_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Registration_Name3 {
            get {
                return ResourceManager.GetString("Registration_Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Author name.
        /// </summary>
        internal static string Registration_Name4 {
            get {
                return ResourceManager.GetString("Registration_Name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Account.
        /// </summary>
        internal static string Registration_PaymentAccount {
            get {
                return ResourceManager.GetString("Registration_PaymentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Author:.
        /// </summary>
        internal static string Registration_Summary {
            get {
                return ResourceManager.GetString("Registration_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With price:.
        /// </summary>
        internal static string Registration_Summary2 {
            get {
                return ResourceManager.GetString("Registration_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string Registration_Summary3 {
            get {
                return ResourceManager.GetString("Registration_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Registration.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay from Account.
        /// </summary>
        internal static string Renewal_Account {
            get {
                return ResourceManager.GetString("Renewal_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author to renew.
        /// </summary>
        internal static string Renewal_Author {
            get {
                return ResourceManager.GetString("Renewal_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm renewal of this author?.
        /// </summary>
        internal static string Renewal_Confirm {
            get {
                return ResourceManager.GetString("Renewal_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Confirm&apos; button, renewal will start.
        /// </summary>
        internal static string Renewal_Confirm2 {
            get {
                return ResourceManager.GetString("Renewal_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated comission.
        /// </summary>
        internal static string Renewal_EstimatedComission {
            get {
                return ResourceManager.GetString("Renewal_EstimatedComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated end date.
        /// </summary>
        internal static string Renewal_EstimatedEndDate {
            get {
                return ResourceManager.GetString("Renewal_EstimatedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose renewal period.
        /// </summary>
        internal static string Renewal_Period {
            get {
                return ResourceManager.GetString("Renewal_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your need specify renewal period.
        /// </summary>
        internal static string Renewal_Period2 {
            get {
                return ResourceManager.GetString("Renewal_Period2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal period.
        /// </summary>
        internal static string Renewal_Period3 {
            get {
                return ResourceManager.GetString("Renewal_Period3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string Renewal_Summary {
            get {
                return ResourceManager.GetString("Renewal_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With price:.
        /// </summary>
        internal static string Renewal_Summary2 {
            get {
                return ResourceManager.GetString("Renewal_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        internal static string Renewal_Summary3 {
            get {
                return ResourceManager.GetString("Renewal_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string Renewal_Summary4 {
            get {
                return ResourceManager.GetString("Renewal_Summary4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Renewal.
        /// </summary>
        internal static string Renewal_Title {
            get {
                return ResourceManager.GetString("Renewal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Transfer_Account {
            get {
                return ResourceManager.GetString("Transfer_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Author.
        /// </summary>
        internal static string Transfer_Author {
            get {
                return ResourceManager.GetString("Transfer_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated commission.
        /// </summary>
        internal static string Transfer_Comission {
            get {
                return ResourceManager.GetString("Transfer_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the transfer of this author?.
        /// </summary>
        internal static string Transfer_Confirm {
            get {
                return ResourceManager.GetString("Transfer_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Confirm&apos; button, transfer will start.
        /// </summary>
        internal static string Transfer_Confirm2 {
            get {
                return ResourceManager.GetString("Transfer_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Author and destination Account.
        /// </summary>
        internal static string Transfer_SpecifyAuthorAccount {
            get {
                return ResourceManager.GetString("Transfer_SpecifyAuthorAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify your author and destination account to transfer..
        /// </summary>
        internal static string Transfer_SpecifyAuthorAccount2 {
            get {
                return ResourceManager.GetString("Transfer_SpecifyAuthorAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering Author:.
        /// </summary>
        internal static string Transfer_Summary {
            get {
                return ResourceManager.GetString("Transfer_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With comission:.
        /// </summary>
        internal static string Transfer_Summary2 {
            get {
                return ResourceManager.GetString("Transfer_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        internal static string Transfer_Summary3 {
            get {
                return ResourceManager.GetString("Transfer_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Author.
        /// </summary>
        internal static string Transfer_Title {
            get {
                return ResourceManager.GetString("Transfer_Title", resourceCulture);
            }
        }
    }
}
