//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Dashboard_Strings", typeof(Dashboard_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug bounty program.
        /// </summary>
        internal static string About_BugBounty {
            get {
                return ResourceManager.GetString("About_BugBounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read about our Bug Bounty program.
        /// </summary>
        internal static string About_BugBounty2 {
            get {
                return ResourceManager.GetString("About_BugBounty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultranet homepage.
        /// </summary>
        internal static string About_HomePage {
            get {
                return ResourceManager.GetString("About_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and terms.
        /// </summary>
        internal static string About_PrivacyTerms {
            get {
                return ResourceManager.GetString("About_PrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the application.
        /// </summary>
        internal static string About_RateApp {
            get {
                return ResourceManager.GetString("About_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate our application in App Store.
        /// </summary>
        internal static string About_RateApp2 {
            get {
                return ResourceManager.GetString("About_RateApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        internal static string About_SendFeedback {
            get {
                return ResourceManager.GetString("About_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your feedback with us.
        /// </summary>
        internal static string About_SendFeedback2 {
            get {
                return ResourceManager.GetString("About_SendFeedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultranet on Telegram.
        /// </summary>
        internal static string About_Telegram {
            get {
                return ResourceManager.GetString("About_Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us in Telegram.
        /// </summary>
        internal static string About_Telegram2 {
            get {
                return ResourceManager.GetString("About_Telegram2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultranet on Twitter.
        /// </summary>
        internal static string About_Twitter {
            get {
                return ResourceManager.GetString("About_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us in Twitter.
        /// </summary>
        internal static string About_Twitter2 {
            get {
                return ResourceManager.GetString("About_Twitter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts_Title {
            get {
                return ResourceManager.GetString("Accounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors_Title {
            get {
                return ResourceManager.GetString("Authors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a PIN.
        /// </summary>
        internal static string CreatePin_Heading {
            get {
                return ResourceManager.GetString("CreatePin_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Dashboard_Accounts {
            get {
                return ResourceManager.GetString("Dashboard_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auctions (outbidded).
        /// </summary>
        internal static string Dashboard_Auctions {
            get {
                return ResourceManager.GetString("Dashboard_Auctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors (renewal needed).
        /// </summary>
        internal static string Dashboard_Authors {
            get {
                return ResourceManager.GetString("Dashboard_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Release.
        /// </summary>
        internal static string Dashboard_LastRelease {
            get {
                return ResourceManager.GetString("Dashboard_LastRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Out.
        /// </summary>
        internal static string Dashboard_LockOut {
            get {
                return ResourceManager.GetString("Dashboard_LockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Dashboard_Products {
            get {
                return ResourceManager.GetString("Dashboard_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases (total/clean/compromised).
        /// </summary>
        internal static string Dashboard_Releases {
            get {
                return ResourceManager.GetString("Dashboard_Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Dashboard_Search {
            get {
                return ResourceManager.GetString("Dashboard_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN or use Fingerprint.
        /// </summary>
        internal static string EnterPin_Heading {
            get {
                return ResourceManager.GetString("EnterPin_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        internal static string EnterPin_Title {
            get {
                return ResourceManager.GetString("EnterPin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Help_No {
            get {
                return ResourceManager.GetString("Help_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related resources:.
        /// </summary>
        internal static string Help_Related {
            get {
                return ResourceManager.GetString("Help_Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was this information useful?.
        /// </summary>
        internal static string Help_WasUseful {
            get {
                return ResourceManager.GetString("Help_WasUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Help_Yes {
            get {
                return ResourceManager.GetString("Help_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold the search bar. Tap the three dots icon More then Settings. Turn Search Box Effects on or off. .
        /// </summary>
        internal static string HelpAnswer_1 {
            get {
                return ResourceManager.GetString("HelpAnswer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_10 {
            get {
                return ResourceManager.GetString("HelpAnswer_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_11 {
            get {
                return ResourceManager.GetString("HelpAnswer_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_12 {
            get {
                return ResourceManager.GetString("HelpAnswer_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_13 {
            get {
                return ResourceManager.GetString("HelpAnswer_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following icons are located in the upper right corner of the screen or in the quick settings panel. To see their names and descriptions, swipe down twice from the top of the screen..
        /// </summary>
        internal static string HelpAnswer_2 {
            get {
                return ResourceManager.GetString("HelpAnswer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_3 {
            get {
                return ResourceManager.GetString("HelpAnswer_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_4 {
            get {
                return ResourceManager.GetString("HelpAnswer_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_5 {
            get {
                return ResourceManager.GetString("HelpAnswer_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_6 {
            get {
                return ResourceManager.GetString("HelpAnswer_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_7 {
            get {
                return ResourceManager.GetString("HelpAnswer_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_8 {
            get {
                return ResourceManager.GetString("HelpAnswer_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_9 {
            get {
                return ResourceManager.GetString("HelpAnswer_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_1 {
            get {
                return ResourceManager.GetString("HelpQuestion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_10 {
            get {
                return ResourceManager.GetString("HelpQuestion_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_11 {
            get {
                return ResourceManager.GetString("HelpQuestion_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_12 {
            get {
                return ResourceManager.GetString("HelpQuestion_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_13 {
            get {
                return ResourceManager.GetString("HelpQuestion_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_2 {
            get {
                return ResourceManager.GetString("HelpQuestion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_3 {
            get {
                return ResourceManager.GetString("HelpQuestion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_4 {
            get {
                return ResourceManager.GetString("HelpQuestion_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_5 {
            get {
                return ResourceManager.GetString("HelpQuestion_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_6 {
            get {
                return ResourceManager.GetString("HelpQuestion_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_7 {
            get {
                return ResourceManager.GetString("HelpQuestion_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_8 {
            get {
                return ResourceManager.GetString("HelpQuestion_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_9 {
            get {
                return ResourceManager.GetString("HelpQuestion_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of active users.
        /// </summary>
        internal static string Network_ActiveUsers {
            get {
                return ResourceManager.GetString("Network_ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth.
        /// </summary>
        internal static string Network_Bandwidth {
            get {
                return ResourceManager.GetString("Network_Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time.
        /// </summary>
        internal static string Network_CurrentTime {
            get {
                return ResourceManager.GetString("Network_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last block date.
        /// </summary>
        internal static string Network_LastBlockDate {
            get {
                return ResourceManager.GetString("Network_LastBlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes count.
        /// </summary>
        internal static string Network_NodesCount {
            get {
                return ResourceManager.GetString("Network_NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round number.
        /// </summary>
        internal static string Network_RoundNumber {
            get {
                return ResourceManager.GetString("Network_RoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network_Title {
            get {
                return ResourceManager.GetString("Network_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications_Title {
            get {
                return ResourceManager.GetString("Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products_Title {
            get {
                return ResourceManager.GetString("Products_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block app.
        /// </summary>
        internal static string Settings_Block {
            get {
                return ResourceManager.GetString("Settings_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After blocking, the application will become not available for download.
        /// </summary>
        internal static string Settings_Block2 {
            get {
                return ResourceManager.GetString("Settings_Block2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying hints.
        /// </summary>
        internal static string Settings_Hints {
            get {
                return ResourceManager.GetString("Settings_Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable secure sign in.
        /// </summary>
        internal static string Settings_SignIn {
            get {
                return ResourceManager.GetString("Settings_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions_Title {
            get {
                return ResourceManager.GetString("Transactions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETH-UNT Transfer.
        /// </summary>
        internal static string Transfers_Title {
            get {
                return ResourceManager.GetString("Transfers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultranet User Center.
        /// </summary>
        internal static string Ultranet_App_Name {
            get {
                return ResourceManager.GetString("Ultranet_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string WhatsNew_Title {
            get {
                return ResourceManager.GetString("WhatsNew_Title", resourceCulture);
            }
        }
    }
}
