//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Dashboard_Strings", typeof(Dashboard_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold the search bar. Tap the three dots icon More then Settings. Turn Search Box Effects on or off. .
        /// </summary>
        internal static string HelpAnswer_1 {
            get {
                return ResourceManager.GetString("HelpAnswer_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_10 {
            get {
                return ResourceManager.GetString("HelpAnswer_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_11 {
            get {
                return ResourceManager.GetString("HelpAnswer_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_12 {
            get {
                return ResourceManager.GetString("HelpAnswer_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_13 {
            get {
                return ResourceManager.GetString("HelpAnswer_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following icons are located in the upper right corner of the screen or in the quick settings panel. To see their names and descriptions, swipe down twice from the top of the screen..
        /// </summary>
        internal static string HelpAnswer_2 {
            get {
                return ResourceManager.GetString("HelpAnswer_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_3 {
            get {
                return ResourceManager.GetString("HelpAnswer_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_4 {
            get {
                return ResourceManager.GetString("HelpAnswer_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_5 {
            get {
                return ResourceManager.GetString("HelpAnswer_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_6 {
            get {
                return ResourceManager.GetString("HelpAnswer_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_7 {
            get {
                return ResourceManager.GetString("HelpAnswer_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_8 {
            get {
                return ResourceManager.GetString("HelpAnswer_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string HelpAnswer_9 {
            get {
                return ResourceManager.GetString("HelpAnswer_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_1 {
            get {
                return ResourceManager.GetString("HelpQuestion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_10 {
            get {
                return ResourceManager.GetString("HelpQuestion_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_11 {
            get {
                return ResourceManager.GetString("HelpQuestion_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_12 {
            get {
                return ResourceManager.GetString("HelpQuestion_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_13 {
            get {
                return ResourceManager.GetString("HelpQuestion_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_2 {
            get {
                return ResourceManager.GetString("HelpQuestion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_3 {
            get {
                return ResourceManager.GetString("HelpQuestion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_4 {
            get {
                return ResourceManager.GetString("HelpQuestion_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_5 {
            get {
                return ResourceManager.GetString("HelpQuestion_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to quickly change Android phone settings.
        /// </summary>
        internal static string HelpQuestion_6 {
            get {
                return ResourceManager.GetString("HelpQuestion_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to understand which settings the icons correspond to the following icons are located in the upper right corner of the screen or in the quick settings panel.
        /// </summary>
        internal static string HelpQuestion_7 {
            get {
                return ResourceManager.GetString("HelpQuestion_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick settings panel makes it easy to navigate and customize options.
        /// </summary>
        internal static string HelpQuestion_8 {
            get {
                return ResourceManager.GetString("HelpQuestion_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to turn animation on or off in the search bar.
        /// </summary>
        internal static string HelpQuestion_9 {
            get {
                return ResourceManager.GetString("HelpQuestion_9", resourceCulture);
            }
        }
    }
}
