//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC.Umc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Product_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Product_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UC.Umc.Properties.Product_Strings", typeof(Product_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Product.
        /// </summary>
        internal static string Products_Register {
            get {
                return ResourceManager.GetString("Products_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products_Title {
            get {
                return ResourceManager.GetString("Products_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Account.
        /// </summary>
        internal static string Registration_Account {
            get {
                return ResourceManager.GetString("Registration_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNT amount.
        /// </summary>
        internal static string Registration_Amount {
            get {
                return ResourceManager.GetString("Registration_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm registration of this product?.
        /// </summary>
        internal static string Registration_Confirm {
            get {
                return ResourceManager.GetString("Registration_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Confirm&apos; button, registration will start.
        /// </summary>
        internal static string Registration_Confirm2 {
            get {
                return ResourceManager.GetString("Registration_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Registration_Name {
            get {
                return ResourceManager.GetString("Registration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Product name. This name will be used like an application domain.
        /// </summary>
        internal static string Registration_Name2 {
            get {
                return ResourceManager.GetString("Registration_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your payment account and Product title.
        /// </summary>
        internal static string Registration_Specify {
            get {
                return ResourceManager.GetString("Registration_Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your need specify your source, destination accounts and amount to transfer.
        /// </summary>
        internal static string Registration_Specify2 {
            get {
                return ResourceManager.GetString("Registration_Specify2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Product:.
        /// </summary>
        internal static string Registration_Summary {
            get {
                return ResourceManager.GetString("Registration_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With price:.
        /// </summary>
        internal static string Registration_Summary2 {
            get {
                return ResourceManager.GetString("Registration_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string Registration_Summary3 {
            get {
                return ResourceManager.GetString("Registration_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Registration.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Search_Author {
            get {
                return ResourceManager.GetString("Search_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Search_Product {
            get {
                return ResourceManager.GetString("Search_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Search.
        /// </summary>
        internal static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Search_Version {
            get {
                return ResourceManager.GetString("Search_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Transfer_Author {
            get {
                return ResourceManager.GetString("Transfer_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated commission.
        /// </summary>
        internal static string Transfer_Comission {
            get {
                return ResourceManager.GetString("Transfer_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the transfer of this Product?.
        /// </summary>
        internal static string Transfer_Confirm {
            get {
                return ResourceManager.GetString("Transfer_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Confirm&apos; button, transfer will start.
        /// </summary>
        internal static string Transfer_Confirm2 {
            get {
                return ResourceManager.GetString("Transfer_Confirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Product.
        /// </summary>
        internal static string Transfer_Product {
            get {
                return ResourceManager.GetString("Transfer_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Product and destination account.
        /// </summary>
        internal static string Transfer_Specify {
            get {
                return ResourceManager.GetString("Transfer_Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify your product and destination account to transfer..
        /// </summary>
        internal static string Transfer_Specify2 {
            get {
                return ResourceManager.GetString("Transfer_Specify2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering Product:.
        /// </summary>
        internal static string Transfer_Summary {
            get {
                return ResourceManager.GetString("Transfer_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With comission:.
        /// </summary>
        internal static string Transfer_Summary2 {
            get {
                return ResourceManager.GetString("Transfer_Summary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Author:.
        /// </summary>
        internal static string Transfer_Summary3 {
            get {
                return ResourceManager.GetString("Transfer_Summary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Product.
        /// </summary>
        internal static string Transfer_Title {
            get {
                return ResourceManager.GetString("Transfer_Title", resourceCulture);
            }
        }
    }
}
