export type OperationType =
  | "category-avatar-change"
  | "category-creation"
  | "category-deletion"
  | "category-movement"
  | "category-type-change"
  | "publication-creation"
  | "publication-deletion"
  | "publication-publish"
  | "publication-unpublish"
  | "publication-updation"
  | "review-creation"
  | "review-edit"
  | "review-status-change"
  | "site-authors-change"
  | "site-avatar-change"
  | "site-moderator-addition"
  | "site-moderator-removal"
  | "site-nickname-change"
  | "site-text-change"
  | "user-registration"
  | "user-unregistration"

export type ExtendedOperationType =
  | Exclude<OperationType, "site-authors-change">
  | "site-author-addition"
  | "site-author-removal"
