@Uccs.Fair.WebApi_HostAddress = http://127.0.0.101:80

### User

GET {{Uccs.Fair.WebApi_HostAddress}}/api/users/65793-0

### Site

GET {{Uccs.Fair.WebApi_HostAddress}}/api/sites/65793-0
Accept: application/json

### Categories

GET {{Uccs.Fair.WebApi_HostAddress}}/api/categories/65793-3
Accept: application/json

### Publication

GET {{Uccs.Fair.WebApi_HostAddress}}/api/publications/65793-2
Accept: application/json

### Publications Search

GET {{Uccs.Fair.WebApi_HostAddress}}/api/sites/65793-0/publications?name=2&page=0&pageSize=10
Accept: application/json
