@Uccs.Fair.WebApi_HostAddress = http://127.1.0.0:1080
@UCCS.Fair.NodeApi_HostAddress = http://127.1.0.0:2900

### Test 1

GET {{Uccs.Fair.WebApi_HostAddress}}/api/sites/67329-0
Accept: application/json

### Test 2

GET {{Uccs.Fair.WebApi_HostAddress}}/api/sites/67329-0/categories
Accept: application/json

### Test 3

GET {{Uccs.Fair.WebApi_HostAddress}}/api/categories/67329-2
Accept: application/json

### Test 4

GET {{UCCS.Fair.NodeApi_HostAddress}}/node/v0/fair/Ping
Accept: application/json

### http://127.1.0.0:2900/v0/vault
### http://127.1.0.0:2900/v0/nexus
### http://127.1.0.0:2900/node/v0/fair